//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolsRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narzedzia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narzedzia()
        {
            this.PozycjeWypozyczenia = new HashSet<PozycjeWypozyczenia>();
        }
    
        public int IDnarzedzia { get; set; }
        public int IDkategorii { get; set; }
        public string NazwaNarzedzia { get; set; }
        public bool Dostepnosc { get; set; }
        public double Cena { get; set; }
    
        public virtual Kategorie Kategorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjeWypozyczenia> PozycjeWypozyczenia { get; set; }
    }
}
