//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolsRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wypozyczenia()
        {
            this.PozycjeWypozyczenia = new HashSet<PozycjeWypozyczenia>();
        }
    
        public int IDwypozyczenia { get; set; }
        public int IDklienta { get; set; }
        public System.DateTime DataWypozyczenia { get; set; }
        public Nullable<System.DateTime> DataZwrotu { get; set; }
        public Nullable<double> Zaliczka { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjeWypozyczenia> PozycjeWypozyczenia { get; set; }
    }
}
